### PR TITLE
Added loading indicators to character select and preview load.

### PR DESCRIPTION
**Pull request by mavisakalyan**
## Describe your changes
- Added a loading indicator to character preview.
- Added a characterLoaded state to AppContext so whenever a new character is selected we can catch that action in any component. 
- Triggered the character loading in the AvatarIcon component so you can see that a new avatar is loading and not just wait for it to change.
## What are the steps for a QA tester to test this pull request?
- Go to character select menu and load some previews.
- Select a new character and see the Avatar Icon loading triggered.
## Issue ticket number and link
https://github.com/webaverse/app/issues/3541
## Screenshots and/or video

https://user-images.githubusercontent.com/55106546/184635079-a78dcf9b-df9c-4224-9c22-7303d92b6f24.mov

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I am not adding any irrelevant code or assets
- [x] I am only including the changes needed to implement the change
- [x] I have playtested and intentionally tried to find error cases but couldn't

### CODE REVIEW

**Comment by mavisakalyan** [comment]
Fixing an error on chrome. Doing a cross browser check.

**Comment by zenkale** [comment]
Looks fine but this Error while we equip the character from character select panel

image

https://user-images.githubusercontent.com/111510128/188156642-4e007abc-d2cd-49d3-84c4-a3b43a255d81.mp4

**Comment by zenkale** [comment]
@mavisakalyan  Looks fine but this Error while we equip the character from character select panel

image

https://user-images.githubusercontent.com/111510128/188156642-4e007abc-d2cd-49d3-84c4-a3b43a255d81.mp4

**Comment by mavisakalyan** [comment]
@zenkale looking into it. Thank you.

**Comment by mavisakalyan** [comment]
@zenkale All fixed please check.

**Pull request closed without merging**
