### PR TITLE
Blended jump animation (WIP)

### PR DESCRIPTION
**Pull request by bru345**

### CODE REVIEW

**Comment by avaer** [comment]
We'll need to resolve conflicts to test.

**Comment by avaer** [comment]
This was superseded by https://github.com/webaverse/app/pull/2316.

Both PRs have been abandoned.

**Comment by avaer** [comment]
Re-opening for code reuse.

**Comment by lalalune** [comment]
Closing this, as @gonnavis seems to have superceded with new PRs.

**Pull request closed without merging**
