### PR TITLE
Fix camera inside head

### PR DESCRIPTION
**Pull request by skaljac**
Fix for camera inside head.

Reopened issue is here:
https://github.com/webaverse/app/issues/1609

Steps for testing:
Use gesture on laptop / mac to zoom in / out
When avatar gets decapitated it should not be possible to view inside player

### CODE REVIEW

**Comment by skaljac** [comment]
https://user-images.githubusercontent.com/4487857/147790525-ad371317-caed-4d1a-8bb7-4d90f573b391.mp4

This is how it looks now

**Comment by skaljac** [comment]
https://user-images.githubusercontent.com/4487857/147790926-ea918387-2e44-46b4-8349-9d652d2704e4.mp4

**Comment by avaer** [comment]
Can we tighten the bounds? Seems quite a jump still.

**Comment by avaer** [comment]
Closing abandoned PR.

**Pull request closed without merging**
