### PR TITLE
UI Componentization

### PR DESCRIPTION
**Pull request by abeersaqib**
- PR divides the user interface into component and tabs.
- It fixes metamask not logging in issues
- it loads tokens and their previews from their respective chains
- It fixes weird names in the world tokens
- it do not solve the weba-wallet / ux issues ( a seperate PR will come for it)

### CODE REVIEW

**Comment by amnaarshed4224** [comment]
Current Issues:
1-Refreshing the game wipes out all the accounts(both discord,metamsak)


2-Logging out of discord and metamask still shows the assets until the assets window is closed.

logging out on discord still has assets
logout assets

3-logging out of discord shows "Discord Oauth failed" instead to showing "log in"

logoutdiscord

4-Inability to bring in assets from discord/metamask assets to game. Gets this error

err while trying to bring assets from metawallet to game thru dragdrop

5-Metamask login works fine but shows assets which are not actually there in my account



6-Nft previews and avatar preview take long time loading

nft loading

7-Collectable preview (character tab) appears on its original spawn location instead of current location.

Capture

8-Claims box is empty even after a silk claim.



9-changing avatar doesn't changes avatars name its fixed to sheila

**Comment by avaer** [comment]
Is this PR only about componentization, or is it packing new features? There is no description so I don't know what the intent is here.

**Comment by avaer** [comment]
I get recursive spam with this PR: 
image

IMO this PR should be componentization only, not a redo of some subsystems.

**Review by avaer — CHANGES_REQUESTED** [review]
Can we remove all of the parts of this that are not componentization related? They can be separate PRs.

**Comment by abeersaqib** [comment]
Turned off the previews from componentization.

**Review by avaer — CHANGES_REQUESTED** [review]
loader.gif should not be added in a Componentization PR.

**Comment by avaer** [comment]
Closing in favor of new PR.

**Pull request closed without merging**
