### PR TITLE
Press 'R' to log current state to console

### PR DESCRIPTION
**Pull request by lalalune**
I find myself very often having to log the current state of the world, scene, localplayer, etc.

This adds a handy function to webaverse.js to log these things to the console.

### CODE REVIEW

**Comment by avaer** [comment]
R is the drop key.

**Comment by lalalune** [comment]
@avaer capital R only, but I can make it something else -- } ?

**Comment by alisaad673** [comment]
@avaer right now 'p' is the drop key in master

**Comment by lalalune** [comment]
changed to }

**Pull request merged**
