### PR TITLE
`PathFinder` use npc-local space & full 3d voxel map & support flying path.

### PR DESCRIPTION
**Pull request by gonnavis**
Follow: https://github.com/webaverse/app/pull/2298 https://github.com/webaverse/app/pull/2468
Fix: https://github.com/webaverse/npc/pull/2#issuecomment-1059400088

According to @avaer 's guidance, use npc-local space ( start-dest space ) to perform A* algorithm to get straight path result when `start` `dest` not axis aligned and there's no obstacle between them.
image

Old:
image

New:
image

Core changes please see `npc-utils.js` in this comparison https://github.com/gonnavis/app/compare/108492c6db8eb272f6bceb5acc8f5e771c3f675e...6d39539e091563d0d38429764930b3226e802782
Currently is js + wasm overlapBox() version, I'll turn it into pure wasm afterwards.

---EDIT---
Converted to WASM version.
Sibling PR: https://github.com/webaverse/app-wasm/pull/35

### CODE REVIEW

**Comment by avaer** [comment]
> use StartDestSpace to perform A* algorithm to get straight path result when start dest not axis aligned and there's no obstacle between them.

Yes, but I think we should do NPC-aligned voxelization for everything, not just this case. It's probably superior in every way and costs only some small amount of matrix multiplication, but the NPC will always be perfectly aligned with their goal so you won't even notice the voxels.

**Comment by gonnavis** [comment]
Ok, I think I already aligned everything to NPC-local ( start-dest space ).
image

**Comment by gonnavis** [comment]
Implemented full 3d voxel map & A-Star algorithm.

Works fine for flying npc:
image
image
image
image

But need some way to compatible with walking npc:
image

**Comment by gonnavis** [comment]
Made this full 3d version support walking npc too.
image

Todo: Add arg to let user control whether flying or walking path finding.

**Comment by gonnavis** [comment]
Added back `heightTolerance` and seperate it's logics with `voxelHeight` again.

Before: Get stuck when hole height is 1.7: 
image

After: Correctly walk around:
image

**Pull request merged**
