### PR TITLE
Disable moving while doing `activate`.

### PR DESCRIPTION
**Pull request by gonnavis**
Fix https://github.com/webaverse/app/issues/3560

After this PR, disable moving:

https://user-images.githubusercontent.com/10785634/183619938-92608264-7f77-4404-8471-6b7d8b55697c.mp4

Before this PR, sliding:

https://user-images.githubusercontent.com/10785634/183620366-d6191bb1-e244-4c87-bbbc-2e9100041698.mp4

### CODE REVIEW

**Comment by avaer** [comment]
Hm, I don't know if it's best to disable movement. Can we blend instead?

**Comment by gonnavis** [comment]
OK, let me try.

**Comment by gonnavis** [comment]
> Hm, I don't know if it's best to disable movement. Can we blend instead?
> 
> Does that look ok?

Tried to blend https://github.com/webaverse/app/pull/3597 .
The animation itself look ok, just the "remotely grab" issue.

**Comment by lalalune** [comment]
@gonnavis anything else on this PR that is needed? Are we good to move to QA?

**Comment by avaer** [comment]
Closed in favor of https://github.com/webaverse/app/pull/3597 which was merged.

**Pull request closed without merging**
