### PR TITLE
Adding actionability for "jump" action in vehicles

### PR DESCRIPTION
**Pull request by aryasalehi**
## Describe your changes
This PR adds the option to enable "jump" action on vehicles ( sittable apps )
"jumpable" component can be added to the .metaversefile of vehicle apps
```   
{
  "key" : "jumpable",
  "value" : true
},
```
The default value of this component is false

**if you don't add this component/set it to false you can not** jump when you're sitting on a vehicle, if you set "jumpable" to "true" : you should be able to jump when you're sitting on a vehicle and that automatically drops the vehicle

## What are the steps for a QA tester to test this pull request?
Add the component that is mentioned above to a vehicle's metaversfile and set it to true/false and test to see if the gameplay matches.

## Issue ticket number and link
Related : https://github.com/webaverse/app/pull/3524

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I am not adding any irrelevant code or assets
- [x] I am only including the changes needed to implement the change
- [x] I have playtested and intentionally tried to find error cases but couldn't

### CODE REVIEW

**Comment by avaer** [comment]
If these components are mutually exclusive, shouldn't it actually be one component like `jumpBehavior`?

**Comment by alisaad673** [comment]
Works fine. Also we should add this to the vehicles(mount, dragon) repos readme, in order to document it.

**Review by avaer — CHANGES_REQUESTED** [review]
Can we limit this PR to only jump action?

I think vehicle fly is a lot more complicated (helicopter vs plane vs flyable mount), and it would also be very different from the current F god mode fly hack.

**Comment by alisaad673** [comment]
Its working fine on the jump action. Since we are not catering the fly action here, pressing 'f' drops the vehicle

**Comment by lalalune** [comment]
Passing to @memelotsqui to review as part of actionsManager feature

**Comment by rondoor124** [comment]
This PR is waiting for @aryasalehi and @memelotsqui's review as part of actionsManager feature

**Pull request closed without merging**
