### PR TITLE
Resolving #2571 UI: Added preventing page zoom change.

### PR DESCRIPTION
**Pull request by TheoTheDev**
Added preventing zoom page UI by touch-pad gestures.

### CODE REVIEW

**Review by 0reo — COMMENTED** [review]
code makes sense, i don't have a touch device which can test this though

**Comment by ohmed** [comment]
> code makes sense, i don't have a touch device which can test this though

Actually the issue originally was about issue on laptop and touchpad, where you using pinch could zoom UI.

**Comment by avaer** [comment]
Is this the best way? Can't this be controlled with CSS rather than locking up the main thread?

**Comment by alisaad673** [comment]
This is working fine. I am no more getting UI zoom in/out through pinching on touchpad.

**Comment by avaer** [comment]
PR is abandoned for now.

**Comment by TheoTheDev** [comment]
> Is this the best way? Can't this be controlled with CSS/meta rather than locking up the main thread?
> 
> https://stackoverflow.com/questions/4389932/how-do-you-disable-viewport-zooming-on-mobile-safari

this doesn't work actually for pitching on mac-book touchpad at least.



> PR is abandoned for now.
WTF ?

**Pull request closed without merging**
