### PR TITLE
One click play a full attack animation & continue combo. ( 2nd try )

### PR DESCRIPTION
**Pull request by gonnavis**
Follow: https://github.com/webaverse/app/pull/2804 , https://github.com/webaverse/app/pull/2804#issuecomment-1096711630 , https://github.com/webaverse/app/pull/3082

- Apply the same one-click logic ( check known animation duration in `update()` ) as https://github.com/webaverse/app/pull/3082 to combo attacks, instead of `animationEnd` events.
- Update to continuous combo attack animations, which compatible with this logic.
- Use `avatar.useAnimations.pickUpThrow.duration` instead of `const throwAnimationDuration`.

### CODE REVIEW

**Comment by msm0823** [comment]
The avatar is unable to move in street scene. You can see even the dash function is not working properly. Can't pick the sword from street scene.



https://user-images.githubusercontent.com/104460803/171660599-cf36e67a-5a1a-4263-88c7-836e5cafdb72.mp4

**Comment by msm0823** [comment]
After switching the scene, I'm able to equip Bow from the tree house scene. The functionality is not working on the bow weapon.

https://user-images.githubusercontent.com/104460803/171660834-6b2e0d9a-b0ce-4c07-a917-97363f2e6c4f.mp4

**Comment by gonnavis** [comment]
@msm0823 Thanks for testing!
Sorry, I have not emphasised that, the one click logic is only applied to sword and silsword in this PR.
So it's correct that the bow and other weapons keep the existing behavior.

**Comment by msm0823** [comment]
> @msm0823 Thanks for testing! Sorry, I have not emphasised that, the one click logic is only applied to sword and silsword in this PR. So it's correct that the bow and other weapons keep the existing behavior.

Got it! Thanks for the clarification!

**Pull request closed without merging**
