### PR TITLE
smooth speed based animations

### PR DESCRIPTION
**Pull request by Loryhoof**
https://github.com/webaverse/app/issues/1842
https://github.com/webaverse/app/issues/1843

https://user-images.githubusercontent.com/29487929/143324388-f590dd2e-0dfc-45fe-886b-fb7493abd948.mp4

https://user-images.githubusercontent.com/29487929/143324422-12b16f04-5b4f-4e44-8c4d-01964f5781de.mp4

Hovercraft wings fold out/in slower/faster at different speeds,  and smooth in and out of animations.

**For QA**

* Test if hovercraft and dragon-mount work as in the video
* Test if animations fail/freeze at any point

### CODE REVIEW

**Comment by avaer** [comment]
I think the hopping is still a bit off. It is hopping while standing still.

**Comment by Loryhoof** [comment]
https://user-images.githubusercontent.com/29487929/143461652-4a995776-8fa3-42e8-8a93-b23f2f28a94c.mp4

**Comment by amnaarshed4224** [comment]
1-The dragon keeps hoping while standing. Also, the camera view that hops along with dragon doesn't seems right.

https://user-images.githubusercontent.com/35926530/143492295-6c15df17-ce9d-496f-b293-08e9df51d764.mp4

2-The speed of the dragon and hovercraft without pressing shift is slow. with pressing shift, its fine.
without shift:

https://user-images.githubusercontent.com/35926530/143492379-5505ed20-1311-4f7d-a5d4-c3236fd4894c.mp4

with shift:

https://user-images.githubusercontent.com/35926530/143492428-ac6ef59b-c893-4e4f-8205-2cc58d199e75.mp4


3-While riding the dragon, hovercraft if the Fly toggle is pressed, it simply goes up in the air. But the dragon and hovercraft, cannot be rode again as theirs no 'E' button. And the avatar is also able to pass through the vehicles.

https://user-images.githubusercontent.com/35926530/143492332-49f54f41-9a3b-43b4-80fb-e46ca9e51a8d.mp4

I am not sure what is the reason that PRs work fine without issues on your side but not on our side.

**Comment by avaer** [comment]
Abandoned PR.

**Pull request closed without merging**
