### PR TITLE
Add cryptoavatars on character select component using CA API.

### PR DESCRIPTION
**Pull request by luixxma**
Added CryptoAvatars characters on CharacterSelect component.

Support pagination, ownership, opensource & collection filter.

Characters that you don't own and aren't open source are blocked from being selectable.

This is a video showing funcionalities.
https://drive.google.com/file/d/1KdzDJeUh8VUdghGT1SC0CFUz0WcRKpy2/view?usp=sharing

### CODE REVIEW

**Comment by alisaad673** [comment]
Functionality Wise its working perfectly Fine. Just some issues related to UI

**1-If we can have the same arrow hovering over the characters once we hover our mouse over them or select them, It would look more in sync with the webaverse character select UI.**

image


**2-As you can see, the preview size for CA characters is much bigger and appears out of the screen, If we can reduce it to the size same as Webavers character's preview size, It would be great.**

image
image


**3-Once we select more then 5 characters per page, We are unable to scroll the UI to select the avatars that are beneath the preview or that are under the first line. So we either need to add scroll bar to it, or we should remove the option to increase characters per page.**

https://user-images.githubusercontent.com/35926530/174667011-0786c86a-e3fd-4ecd-9cde-27297dd0609e.mp4


**4-We need to improve this UI for it to be more in sync with webaverse UI.**

image

**Comment by lalalune** [comment]
Assigning this to ultrabot

**Comment by lalalune** [comment]
Hey @alisaad673 could you review this? if there's anything left to do we can hand it to Ultrabot to finish, in Discord it was mentioned this should be good to go :)

**Comment by alisaad673** [comment]
Hey @lalalune Out of the above issues I have pointed out, Number 2 seems to be fixed. Remaining are still there. So we need to fix them.

**Comment by alisaad673** [comment]
The Ui seems to be working but it has a few other issues now. Firstly, if this can be rebased over to latest master, it can be tested properly .

1- The arrow selector and square selectors for the character do appear when we parse over them only for the first time we open the character select option. Once we equip any of the vrm, and then we open the character select tab,
        -We are unable to select any of our own characters
        -No arrow selectors appear over any of our own characters
        -No square selector appears on the cryptoavatars characters although we are able to select their characters
        
https://user-images.githubusercontent.com/35926530/180007432-4542e19e-56c1-43bf-badd-eeda12e6af23.mp4

2-The diorama previews for our own characters are appearing weird as you can see in the video that once we are close to a certain point(close to mirror) the diorama appears fine while once we get away from it, the view also gets distorted and appears from far away, as if the point of snapshot is fixed. This is working fine for Cryptoavatars characters.

https://user-images.githubusercontent.com/35926530/180008597-95e0926b-b1e9-4d71-b51c-e6e4164c6ac8.mp4

3-While we parse over the empty token's boxes:
        -It throws these errors
        -Also there appears the arrow selector at weird position while, the mouse is at another position
         
image

https://user-images.githubusercontent.com/35926530/180009615-721f9d59-8261-4e2f-963c-6c719f7030dc.mp4

4- This is not much of an issue but we are also able to equip the premium avatars(the ones with a disable sign on them) of Cryptoavatars, though they said they can be accessed.

**Comment by lalalune** [comment]
Close in favor of https://github.com/webaverse/app/pull/3305

**Pull request closed without merging**
