### PR TITLE
No autoupdate fix - Performance part 1

### PR DESCRIPTION
**Pull request by yaserOSource**
This PR manually calls object.updateMatrixWorld. 

Object3D.DefaultMatrixAutoUpdate = false;. will be something i will add next after this PR.

This PR has a dependency on this totum PR, as such must be checked out in packages/metaversefile(soon to be called metaversefile/totum):
https://github.com/webaverse/totum/pull/42

There is also a dependency on all of the apps. 

All the relevant scene apps are pointing to my repository for ease of testing purposes, and will be merged into webaverse/[sceneapp] with a PR after code review.

### CODE REVIEW

**Review by avaer — APPROVED** [review]
Code looks good, though we shouldn't merge until the individual apps are merged.

**Comment by avaer** [comment]
Found lots of bugs so far:

- glbb type positioned wrongly
image

- `E` does not update
image

- Chest does not animate at all
image

- Damage mesh does not move
image

I haven't even gotten started with testing, so it looks like there are many regressions to fix still.

**Comment by yaserOSource** [comment]
image

glbb placement looks correct on mine

**Review by avaer — APPROVED** [review]
Code still looks good, but I recommend thorough testing.

That includes the screenshot system, since this touches it.

**Pull request merged**
