### PR TITLE
Base for new UI & base for Minimap & Hotbar.

### PR DESCRIPTION
**Pull request by ohmed**
- Adding base placeholder for new Minimap.
- Adding base placeholder for new Hotbar menu.
- Structure clean up.

image

### CODE REVIEW

**Comment by avaer** [comment]
This PR looks ok, but it's not actually doing anything. It's creating a separate app.

Can we get this but part of the main app?

**Comment by avaer** [comment]
Also, missing description.

**Review by avaer — APPROVED** [review]
Code looks good to me.

@amnaarshed4224 can you see if there are any regressions?

**Comment by avaer** [comment]
UI PR's should at minimum have screenshots or a note as to what changed, or else it is impossible to test.

**Comment by ohmed** [comment]
Updated description.

**Comment by amnaarshed4224** [comment]
I have tested the major functionalities
-No new errors or warnings
-Scenes loading fine
-Voice packs fine
-Both Logins working fine
-Character tab works fine
-Equipping items works fine

The stats panel appears beneath the minimap placeholder.
Everything Else seems fine.

**Pull request merged**
