### PR TITLE
[WIP] Screenshot iframe2

### PR DESCRIPTION
**Pull request by abeersaqib**
In App Preview service that open iframe from the weba.online. weba.online uses the dashboard worker to point to the weba.com 

It has it's own queuing systme and can use it based on the load.

### CODE REVIEW

**Comment by avaer** [comment]
Is this for https://github.com/webaverse/app/issues/1896 ?

**Comment by abeersaqib** [comment]
> Is this for #1896 ?

Yes it's for the same PR. it requires worker to be fixed for the QA testing.

**Comment by avaer** [comment]
We don't need to fiddle with CloudFlare Workers. If that's too hard, we can just start a server which will `node-http-proxy` and add the headers we need.

**Comment by abeersaqib** [comment]
> We don't need to fiddle with CloudFlare Workers. If that's too hard, we can just start a server which will `node-http-proxy` and add the headers we need.

Yeah exactly. But i made it work thanks to your proxy suggestion.

**Review by avaer — APPROVED** [review]

**Pull request merged**
