### PR TITLE
Resolving #2571 UI: Added preventing page zoom change.

### PR DESCRIPTION
**Pull request by TheoTheDev**
Sequel of https://github.com/webaverse/app/pull/2706

Meta & CSS params added to prevent zoom by pitch on touchpad.
JS code to prevent zoom by pitch on Mac touchpad [only this can prevent zooming on mac from my experiments].

### CODE REVIEW

**Comment by 0reo** [comment]
no obvious code issues, can be moved to manual QA

**Review by 0reo — COMMENTED** [review]
no obvious code issues, can be moved to manual QA

**Review by avaer — CHANGES_REQUESTED** [review]
Same code issues as before.

**Comment by 0reo** [comment]
@avaer using the wheel event seems to be the preferred way to address this for apple devices
https://bugs.webkit.org/show_bug.cgi?id=145214

and webkit has explicitly disabled `user-scalable=no`
https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/

**Comment by avaer** [comment]
> using the wheel event seems to be the preferred way to address this for apple devices

Does it require locking the event to the main thread for all browsers?

**Comment by TheoTheDev** [comment]
> > using the wheel event seems to be the preferred way to address this for apple devices
> 
> Does it require locking the event to the main thread for all browsers?

Can you explain ? this is not a complex operation in any way and won't be blocking anything.

**Comment by avaer** [comment]
> Can you explain ? this is not a complex operation in any way and won't be blocking anything.

`passive: false` changes when and how the event is handled (it will block the frame loop).

**Comment by TheoTheDev** [comment]
> > Can you explain ? this is not a complex operation in any way and won't be blocking anything.
> 
> `passive: false` changes when and how the event is handled (it will block the frame loop).

without 'passtive: false' it won't work. it's the way it works.
no not-passive - no fix.

**Comment by avaer** [comment]
Ok, I guess we can't fix this in that case.

**Pull request closed without merging**
