### PR TITLE
Disable crouch when player has narutoRun action or sit action.

### PR DESCRIPTION
**Pull request by tcm390**
Disable crouch when player has `narutoRun` action or `sit` action.

related
https://github.com/webaverse/app/issues/3427
https://github.com/webaverse/app/issues/3395

### CODE REVIEW

**Review by avaer — APPROVED** [review]

**Comment by avaer** [comment]
Needs regression testing.

**Comment by alisaad673** [comment]
Works Fine.
 @tcm390 can you also disable crouch mode while dancing?

https://user-images.githubusercontent.com/35926530/182442258-4adb97fe-5007-47d5-b765-b6389dac3b57.mp4

**Comment by tcm390** [comment]
[disable crouch when dancing](https://github.com/webaverse/app/pull/3446/commits/248f2de3acbb9f8817945648ffd9bd0e3ebc0352)

**Review by avaer — CHANGES_REQUESTED** [review]
There are many of this class of bug. I don’t think this is the right fix.

The actions system needs to go through an actions manager which cleans up conflicting actions.

**Comment by lalalune** [comment]
@memelotsqui can pick this up with impending update to https://github.com/webaverse/app/pull/3551

**Pull request closed without merging**
