### PR TITLE
fix position

### PR DESCRIPTION
**Pull request by ChrisEddy**

### CODE REVIEW

**Comment by avaer** [comment]
I don't think meshes failing to load should be ignored. We should make sure a placeholder is loaded.

**Review by avaer — CHANGES_REQUESTED** [review]
Should make sure a proper placeholder is loaded instead in `loadFileForWorld`.

**Comment by avaer** [comment]
Is this one still valid?

**Comment by ChrisEddy** [comment]
was a trash pr

**Pull request closed without merging**
