### PR TITLE
Reduce sonic boom material and pre-compile

### PR DESCRIPTION
**Pull request by tcm390**
Reduce 5 sonic boom materials and add precompile for the material

testing video: (use `material.onBeforeCompile` to test it)
Before adding precompile:

https://user-images.githubusercontent.com/60634884/181802905-8c599b4d-bd4e-4921-8204-d007c76cc0d4.mp4

After adding precompile:

https://user-images.githubusercontent.com/60634884/181802961-ecb04b44-2e05-48ef-b32b-8d2ca83b6d26.mp4

### CODE REVIEW

**Comment by avaer** [comment]
Since we are optimizing, these textures should be KTX2.

**Comment by tcm390** [comment]
use KTX2 texture
[use ktx2 texture](https://github.com/webaverse/app/pull/3415/commits/dd86f642999cfc59e0f1051cfacad83d8ee09637)

**Comment by alisaad673** [comment]
I tried to test it, 
Total resources being used in master: 354mb with sonic boom
Total resources being used in this branch: 354mb with sonic boom

I don't see any reduction in resources. Also not much difference in load time.

**Comment by lalalune** [comment]
@alisaad673 memory isn't going to go up or down. it's really -- does it hiccup when you start sonic booming?

in the current app it does, because it's compiling shaders n stuff. on my linux machine i get a drop to 2 FPS. if the shaders are precompiled it should feel smooth, with no hiccups.

**Comment by tcm390** [comment]
[convert degree to radian and remove THREE.Math.randFloatSpread](https://github.com/webaverse/app/pull/3415/commits/3ee25342b2f6e7e9bee66d198751a9d129b90709)

this is the result:

https://user-images.githubusercontent.com/60634884/183216815-b16dcf21-a9fb-42fc-a09e-32bb46545c4b.mp4

**Comment by tcm390** [comment]
re write in this PR
https://github.com/webaverse/app/pull/3587

**Comment by tcm390** [comment]
Closed
Duplicate of this merged PR https://github.com/webaverse/app/pull/3667

**Pull request closed without merging**
