### PR TITLE
Added UI for ActionMenu and Settings panel.

### PR DESCRIPTION
**Pull request by ohmed**
- Core UI added.
- All settings are saved/loaded.
- Only 'Character details' gfx settings are actually applied.

image
image
image
image
image

Known issue: when changing 'Character details' lower -> higher it creates multiple levels of avatar in the scene.

### CODE REVIEW

**Comment by avaer** [comment]
The settings panel looks cool, but can we clean up those top-right buttons? There are too many styles going on there IMO. It could be the simple boxes for now.

**Comment by avaer** [comment]
Looks like it has different font size. Other than that, looks good.

@amnaarshed4224 can you check it out?

**Comment by amnaarshed4224** [comment]
@ohmed can you do it on the latest master, Actually This PR has this issue of avatar not being able to move. Another PR was causing this issue, Its reverted. Due to movement disabled, I am unable to test the app for any regressions and for character details too.

Some issues that can be addressed right now are:
1-The font size of new components(Settings, Mode ) seems different as compared to the already existing ones(World, Login, Character tab).
2-The new components do not get highlighted when curser is over them. They should get highlighted like the already existing ones.

highlight

3-The hotbar UI is previous one, as avaer asked to use the already existing one.

items panel

4-Once we are inside settings panel, clicking anywhere makes the curser go into the game, We need to press "Esc" to get cursor back. It should be disabled.(Sorry, for some reason cursor isnt appearing in the screen recording.)

https://user-images.githubusercontent.com/35926530/154518261-27b4a0ac-7888-4b2a-bbe9-05c4c458ae40.mp4

**Comment by ohmed** [comment]
@amnaarshed4224 All requested changes done.

**Comment by avaer** [comment]
This PR updates totum for some reason. Bad merge? It would cause the above error.

**Comment by avaer** [comment]
Can we delete the images that are no longer used?

https://github.com/webaverse/app/pull/2370/files#diff-c4e4e6d1e339269040a15f6a2d52ba5147547d9e05441e912c6d4ea54bf18597

**Comment by ohmed** [comment]
Synced with master again and removed unneeded image.
image
No issue on my side [latest master merged, lates totum pulled].

**Comment by avaer** [comment]
The font size is still not the same for all of the buttons.

image

**Review by avaer — APPROVED** [review]

**Pull request merged**
