### PR TITLE
Formalize same UI for 'inventory' and 'From upstreet' items

### PR DESCRIPTION
**Pull request by mavisakalyan**
## Describe your changes
- made both lists in the inventory and upstream to look the same have similar structure so we are consistent with the design. Only difference is the highlight.
## What are the steps for a QA tester to test this pull request?
- find some items to add to your claims list and check both lists, inventory and from upstream in the account tab. Both lists should be the same in structure with color differance.
## Issue ticket number and link
https://github.com/webaverse/app/issues/3388
## Screenshots and/or video
Screen Shot 2022-08-09 at 19 51 06
Screen Shot 2022-08-09 at 19 51 16

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I am not adding any irrelevant code or assets
- [x] I am only including the changes needed to implement the change
- [x] I have playtested and intentionally tried to find error cases but couldn't

### CODE REVIEW

**Comment by avaer** [comment]
The orange highlight is not good and was never intended as an actual design. We can do a lot better with e.g. circles or background gradients to indicate categories. The only reason it's like this is it's something I did in 5 minutes a year ago.

**Comment by mavisakalyan** [comment]
Got it let me see what I can come up with.

**Comment by mavisakalyan** [comment]
One question though, should the hover effect be different in color for different tabs? or should we keep one consistent design? @avaer

**Comment by lalalune** [comment]
@mavisakalyan don't worry about hover for now

**Pull request closed without merging**
