### PR TITLE
changed from toJSON to array copy

### PR DESCRIPTION
**Pull request by memelotsqui**
## Describe your changes
-changed toJSON() to make a copy of the the desired array.
-toJSON was entering an infinite loop (I believe it has to do with hitTracker being a property and a parent of an object)

## What are the steps for a QA tester to test this pull request?
1-Equip a Dragon
2-Load a scene
3-Scene should not be crashing

## Issue ticket number and link
#3452 

## Screenshots and/or video

https://user-images.githubusercontent.com/1117257/182483592-ffe0ae98-1ac5-454f-85e1-0315bfcac782.mp4

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I am not adding any irrelevant code or assets
- [x] I am only including the changes needed to implement the change
- [x] I have playtested and intentionally tried to find error cases but couldn't

### CODE REVIEW

**Comment by alisaad673** [comment]
Works fine

**Review by avaer — CHANGES_REQUESTED** [review]
> -toJSON was entering an infinite loop (I believe it has to do with hitTracker being a property and a parent of an object)

This object is the `zjs` state. It must be JSONable, attaching things like THREE.js `Object3D` to it is illegal.

Therefore it seems like some other code is destroying the zjs state object, and we need to fix that.

**Comment by avaer** [comment]
Also, please don't do this for this PR (the zjs state must be serializable so this will not be a legal solution), but there is also the `structuredClone` method: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by memelotsqui** [comment]
Alright!, right now im investigating because I believe the issue comes from HitTracker, thats the one getting called in loop, I will find a different solution to make this JSONable :)

**Comment by avaer** [comment]
Needs a totally different solution, so closing.

**Pull request closed without merging**
