### PR TITLE
Split jump animation to `jump start`, `fall loop` , `land` three stages.

### PR DESCRIPTION
**Pull request by gonnavis**
Fix: https://github.com/webaverse/app/issues/484

https://user-images.githubusercontent.com/10785634/170843102-dae5dc94-7812-48ee-8105-e869b5432246.mp4

Split jump animation to `jump start`, `fall loop` , `land` three stages all by codes now.
If this PR is ok, I'll request artist to remake the `fall loop` animation base on this frame ( frame 39 ):
image
But maybe the current static version is already better, can be used as first version directly.

### CODE REVIEW

**Comment by avaer** [comment]
It's not had, but the fall loop has only one frame?

**Comment by avaer** [comment]
I don't think we should be copying the existing hack. The animation was never good in the first place.

I was expecting a new set of animations that make a lot more sense in fast combat.

**Comment by avaer** [comment]
Additionally, I do think when we redo these jump animations, we should have a good fall loop in it (not static).

**Comment by avaer** [comment]
Gonna close this since I don't think it's worth working on or shipping until we have good animations that are not based on the existing.

**Comment by gonnavis** [comment]
Got it, I'll apply art resources to do a new animation and give some ideas of my own.

**Comment by avaer** [comment]
Thanks! The code for unjump is probably usable too.

Some other points about jumping which might be related:
- The plan for naruto run is that it greatly increases your jump height and gravity, so you can easily jump over tall obstacles with it.
- I think we will have a "stomp" attack, which immediately brings you out of the jump by pressing C in midair.

Both of these will need to interact with the jumps in some way so it is worth factoring it into the animations and animations style.

The above is also the reason the existing Mixamo jump animation is really not good, since it is slow and relaxed, and not really compatible with these kinds of fast gameplay moments.

**Comment by gonnavis** [comment]
Hello @avaer , texta has already made one new jump animation, how about it?

https://user-images.githubusercontent.com/10785634/170889857-703a13bc-a877-4a0e-b046-d96da5c4fdb2.mp4

**Pull request closed without merging**
