### PR TITLE
Remove import maps

### PR DESCRIPTION
**Pull request by avaer**
This PR removes import maps from the `html` and `js` files.

External objects will need to be updated to support this.

Fixes https://github.com/webaverse/app/issues/1375.

### CODE REVIEW

**Comment by avaer** [comment]
Now this needs testing that all of the `html` files are correctly loading.

The external modules still need to be updated.

**Review by AGoblinKing — APPROVED** [review]
LGTM. I ran a codespace against it and didn't encounter issues. I only hit index.html, I'll test the others.

**Comment by AGoblinKing** [comment]
image
Looks like editor.html is having issues with html-render

**Comment by avaer** [comment]
> Looks like editor.html is having issues with html-render

Ah yup that needs to be patched!

**Pull request merged**
