### PR TITLE
Sound manager implementation,game sfx   WIP

### PR DESCRIPTION
**Pull request by skaljac**
This is related to issue:
https://github.com/webaverse/app/issues/1633

sound-manager.js implements sound subsystem for this game.

We now have sound for footsteps (walking and running), jump start sound, jump end sound.

Steps for testing:
walk around - footstep sound should play
run - footsteps should be faster
jump - there should be a sound for jump and jump end

### CODE REVIEW

**Comment by amnaarshed4224** [comment]
Yes, The sounds are working fine. Just as it is supposed to be.

**Comment by avaer** [comment]
Are we making sure to synchronize the footsteps perfectly with the animation?

Doing that should actually not be hard, since the animation loop is very well defined, and the time of the feet hitting the ground in the animation is consistent, purely based on the current game time.

**Comment by avaer** [comment]
Loading all animations in avatars.js: https://github.com/webaverse/app/blob/a5346a446e519283317f746a2e7856c59c9c3fae/avatars/avatars.js#L223
Animation timing is based purely on the render loop current world time, so we can know perfectly when there is a foostep: https://github.com/webaverse/app/blob/a5346a446e519283317f746a2e7856c59c9c3fae/avatars/avatars.js#L1628

**Comment by avaer** [comment]
Implementation notes:

- this looks like it's loading one copy of each sound, which means probably you can't play the same sound twice (the second hit will cut off the first one?)
- MP3 or OGG is probably better than WAV, especially as the amount of sounds increases.

**Review by avaer — COMMENTED** [review]
Overall looks good.

**Comment by skaljac** [comment]
I have change file format to .ogg
Also, as suggested we now have synchronization with steps for footstep sounds

**Comment by avaer** [comment]
Maybe mp3 is better if we check the compatibility tables: https://caniuse.com/?search=ogg

**Comment by skaljac** [comment]
I have changed file format to .mp3 it works fine in chrome, chrominum

**Comment by amnaarshed4224** [comment]
This PR works Perfectly fine with sounds of footsteps while running/walking. The footsteps are too in synchronization with animation. So, its ready for merge if there are no code changes left.

**Comment by amnaarshed4224** [comment]
This PR works Perfectly fine with sounds of footsteps while running/walking. The footsteps are too in synchronization with animation. So, its ready for merge if there are no code changes left.
1-One thing that should be in your notice is hovercraft and dragon have same footsteps sound right now. Might needs to be changed.

**Comment by skaljac** [comment]
Ok, I need to change that in this PR

**Comment by skaljac** [comment]
This problem with fly,jump,sit state of player and step sound is now fixed

**Comment by amnaarshed4224** [comment]
Yes, Its working perfectly fine now.

**Review by avaer — APPROVED** [review]

**Pull request merged**
