### PR TITLE
Old terrain code

### PR DESCRIPTION
**Pull request by koreex**

### CODE REVIEW

**Comment by koreex** [comment]
Added terrain to default-scene

**Comment by koreex** [comment]
Mipmaps fixed

**Review by avaer — CHANGES_REQUESTED** [review]
The terrain should be separated into its own app, not inside `default-scene`.

It can then be loaded from there: https://github.com/webaverse/app/blob/697074da2dd52ab3ddb944072bf8b5fe51d8c2c0/metaverse_modules/default-scene/index.js#L121

**Comment by yszhao91** [comment]
https://github.com/webaverse/app/pull/2575/commits/e8cacdc08466e388eead4644be45930f4cd479c0
WeChat Screenshot_20220326221807

**Comment by koreex** [comment]
Generate terrain using worker

**Comment by yszhao91** [comment]
1.IdTech.js

use Texture2D Array to load multiply textures in one;

use Id to index texture,reduce use texture uniform

loadAll load all Under the same directory image file





2.toonMaterial.js

randomTexture ：

texture random sampler 


 
. material base on MeshToonMaterial

USE_TERRAIN material base on toonMaterial

exportconstterrainMaterial = newTHREE.MeshToonMaterial({    color:0xaaccff, gradientMap:gradientMaps.threeTone });;

terrainMaterial.onBeforeCompile = (shader, renderer) => { 

    shader.defines = shader.defines || {};

    //open Terrain render
    shader.defines['USE_TERRAIN'] = '';
 ; 
}
add noise detail



Triplaner texture

    //triplanar Texture
    vec4 triplanarTexture(vec3 pos, vec3 normal,vec3    blending, float texId, sampler2DArray tex,float scale)  

    //triplanar normal 
    vec3 triplanarNormal(vec3 pos, vec3 normal,vec3     blending, float texId, sampler2DArray tex,float scale);
stylized (toon)

    //use gradientMap generate toon tone
    getGradientIrradiance()
final:

**Comment by avaer** [comment]
We shouldn't pack all of the textures into the repo. This will need to be rebased and purged, or it will drastically increase the repository size.

**Pull request closed without merging**
