### PR TITLE
Threejs update to r143

### PR DESCRIPTION
**Pull request by avaer**
Dependents:

https://github.com/webaverse/three/tree/r143
https://github.com/webaverse/three-vrm/pull/5
https://github.com/webaverse/totum/pull/124

https://github.com/webaverse/street/pull/10
https://github.com/webaverse/street-base/pull/5
https://github.com/webaverse/mirror/pull/9
https://github.com/webaverse/floating-island/pull/8
https://github.com/webaverse/basiheart/pull/1
https://github.com/avaer/shield/pull/1

### CODE REVIEW

**Comment by avaer** [comment]
Although this currently works, I think the actual `three` and `three-vrm` need to be re-done to ensure quality.

There were a lot of bugs in the original port which makes it hard to trust that it was done correctly.

Additionally, we should maintain a history lineage with `three.js` (the https://github.com/webaverse/three/tree/r143 branch is currently not related).

**Comment by avaer** [comment]
I also think the VRM colors need to be fixed since they are different in this PR.

**Comment by alisaad673** [comment]
Issues:

### 1-Sonic Boom regressed in street.scn

https://user-images.githubusercontent.com/35926530/183977741-38f83eb9-c973-4157-972b-4c4a0254154f.mp4

### 2-Water is broken totally:

https://user-images.githubusercontent.com/35926530/183984191-ce8d58f7-aa4a-47fd-9ba5-efbda599a966.mp4

### 3-Error while switching from water.scn:

image

### 4-Grass.scn throwing this:

image

### 5-Classroom.scn vrchat issue:

image

### 6-Switching the vrm to miku in block, canyon, prototype scenes, crahses the app:

image

### 7-Skybox(twilight-sky) not loading in silk-fountains.scn , crypt.scn and spacpod.scn

image

### 8-Equip vrm(phetaplushi) in clockrealm.scn crashes the app:

image

### 9-Moon.scn and asteroid-game.scn wont load:

image

--------------------------------------------------------### Lightning Issues--------------------------------------------------------------

### 10-Lightning in treehouse.scn seems darker on the avatar:

image
image

### 11-Lightning issue on avatars in batalion.scn:

image

### 12-Lightning issue in gunroom.scn

image

### 13-Lightning issue in canyon.scn

image

### 14-Lightning issue in silk-fountains.scn

image

### 15-Lightning issue in spacedoodles.scn:

image

### 16-Lightning issue on vrm in parkour.scn:

image

**Comment by avaer** [comment]
Merged in labs!

**Pull request closed without merging**
