### PR TITLE
[WIP] New Architecture

### PR DESCRIPTION
**Pull request by abeersaqib**
### Working 

- Build process using esbuild, rollup & vite.
- Serving of compiled assets.
- Realtime compile server and transform server for Metaverse-Modules and loading.
- Everything else :)

### Not Working

- `metaverse_modules/error-placeholder/` (error is linked to `BufferGeometryUtils.mergeBufferGeometries` which is not a top level module and will need to be defined as entry level module to make this error resolved).

- toroika worker giving ambixious error (error linked to usage of import.meta.url which is not available after the compile)

- Audio worklet dynamic loading (`packages/wsrtc/ws-audio-conetext.js. L#11`) (error linked to usage of import.meta.url which is not available after the compile)

#### `index.mjs`

- The file implements additional functions to support the production mode. It uses the `-p` flag to know whether it's in production mode or development mode. if the file is in development mode it will pass the request to the vite ssr server and will leverage the dynamic compile. 
- If the server is in production it will serve the assets under the `dist` and dynamic assets are compile through the function `dynamicImport` 
- `dynnamicImport` helper function simply calls the `metaverserfile`'s rollup.js and leverage it's `resolveId` and `load` to serve the module. 

#### `Rollup.JS`

- Whenever a module is dynamically loaded it's inside an environment where it don't the exact paths of the `Metaversefile` & `Three` so a new Babel Transformation is added for all of the metaverse modules that changes the path of the imports dynamically. 

#### `ModuleRewrite` 

- Babel transform passes the path of the moduleRewrite file which process the import path and change them with the server path dynamically. 
- Paths are matched so there won't be duplicate instances of metaversefile or ThreeJS

#### `Vite.config.js`

-  Detailed description will be added shortly.

### CODE REVIEW

**Comment by amnaarshed4224** [comment]
1- The app is not loading for me, i am not sure if its in the PR or i am doing something wrong?
First of all, while i try to pull the latest, its giving this error, though the branch is upto date with latest. I still ran it through "npm run build", "npm run dev".



2-I am only getting a blank screen that keeps loading. Also this is a quite old version of master that this branch is on.



3-I am getting these errors and warnings

**Comment by amnaarshed4224** [comment]
| Feature      | Status | explanation |
|-------------|--------|--------|
| walking      | working |
| Running   | working |
| Dash         | working |
| Scene switching  | sometimes works sometimes doesn't |
| crouch walk   | working |
| equipping items  | partially working | "E" activator doesn't appears while being close to item, But we can still equip it |
| sword action  | working |
| All assets loading | not working | most of the assets are not loading|
| Character panel  | working |
| jumping  | working |
| riding vehicles  | working |
| pet  | working |
| avatar switching| working |no E activator, but we are able to switch|
| discord login| working |
| metamask login| not working | 


1- The branch is on a quite old version of master, i wasn't able to test most of the new features.
2- Overall the scene switching is not smooth at all. The app breaks in between scene switching sometimes. And then even reloading it doesn't works. We have to rebuild and re run it again through terminal.
3-There are too many errors in each scene. I will try to put Screenshots here:
Street scene:





Treehouse:




shadows:


grass:
Grass doesn't loads
grass

Gunroom:
Avatar unable to move

Silkfountains:
No Assets except sky gets loaded

silfountains

**Comment by amnaarshed4224** [comment]
| Feature      | Status | explanation |
|-------------|--------|--------|
| avatar able to move in all scenes|not working | not working in street scene|
| walking      | working |not working in street scene|
| Running   | working |not working in street scene|
| Dash         | working |not working in street scene|
| jumping  | working |not working in street scene|
| crouch walk   | working |not working in street scene|
| sword and potion animation  | partially working |Couldn't test Sword as it isn't loading in treehouse.scn and avatar isn't moving in street scene|
| All assets loading | partially working| Not in treehouse.scn|
| All scenes loading | partially working| classroom.scn isn't working|
| Scene switching  | Working |
| equipping items  | Working | 
| Character panel  | working |
| riding vehicles  | working |
| pets  | working |
| avatar switching| working |
| discord login| working |
| metamask login| working | 
| Options avatar styles| working | 
| Diorama| working | 

Errors and warnings in scenes:
1-Avatar is unable to move in street scene. All other scenes are working quite fine, Just a few errors.
2-Treehouse scene has some asset loading issues.
3-Darkness scene takes a bit longer before avatar can move. unlike other scenes.

Other major functionalities seems to work fine.

Street scene:
street
street 2

Treehouse:
Treehouse
Particle mesh:
treehouse particle mesh
silsword:
treehouse sislword
infinitifruit
treehouse infinitifruit

Shadows.scn:
shadows

Grass.png:
grass

Classroom:
Happens in latest master too.
classroom
classroom vr

**Comment by abeersaqib** [comment]
Closing in favour of new PR

**Pull request closed without merging**
