### PR TITLE
Resolves #2593 UI: Updated Setting panel fade-in/out.

### LINKED ISSUE #2593: Settings panel fade
The settings panel fade is not very good, and not in line with the rest of the app.

We should add a slide or some sort, and make the time to display a lot shorter.

### PR DESCRIPTION
**Pull request by TheoTheDev**
Updated fade in/out animation of Setting panel.
Now it slides same as 'character-select' panel, but half time faster to keep short timing.

### CODE REVIEW

**Review by 0reo — COMMENTED** [review]
logic looks good and works on my end.  but if we're reusing the logic from another panel, should we not have a reusable class for panel fades?

**Comment by ohmed** [comment]
> logic looks good and works on my end. but if we're reusing the logic from another panel, should we not have a reusable class for panel fades?

I also at first had this thought, but the panels have different structure and different behaviour sometimes, different positions, different requirements.
I think reusable class will make things much less flexible and if for example one panel will need some custom update for animation this will lead to 'how the hell' should I change it to work and don't affect other or smth like this.

**Comment by avaer** [comment]
A function component could work for abstract transitions but I agree there are enough different transitions that it might not be worth it.

**Comment by alisaad673** [comment]
Overall works well But can we have the fade out speed same as the fade in speed?

https://user-images.githubusercontent.com/35926530/161328936-5617ff30-5cae-4154-b84e-958a0e52dc26.mp4

**Comment by avaer** [comment]
I think it actually is the same speed, fast. It's just not a transition function that mirrors itself.

One problem is that the opacity and the movement do not follow the same timing functions. Maybe they should?

**Comment by avaer** [comment]
This should have been a trivial change, let's not spend days on it.

**Pull request closed without merging**
